### ISSUE TITLE
Large repo with lots of branches looks weird

### ISSUE THREAD

**Issue by lheinold** [phil294/GitLG#102]
I have a very large repo with a lot of branches, many of which have very long names. It's common to have multiple branches at the same commit.

As I scroll down in my repo, the branch names are offset strangely:
<img width="958" alt="Screenshot 2024-09-05 at 1 41 28 PM" src="https://github.com/user-attachments/assets/ce11ab90-d14c-43a9-9f1e-dba1f74a91b2">

(edit: I realized that I could just edit the text using dev tools instead of marking over identifying information)

I think the name is aligned where it would be in the graph, but it looks random when scrolling (branches can also get pushed off the end of the line completely if you scroll down far enough). 

Can there be a config option to left-align all the branch names, maybe all lining up with the commit messages?

**Comment by phil294** [comment]
they were always placed at the end of the branch visualization lines. In your screenshout you just happened to have the most part of the graph lines cut off. You can drag the area left and right by dragging on one of the colored circles just left to the commit messages.

But either way, like discussed in the other issues, the ref tips are now always left aligned at the start of the commit subject so it should look better now without you needing to do anything.
