### ISSUE TITLE
The curves are intermittent

### ISSUE THREAD

**Issue by heartacker** [phil294/GitLG#105]
![image](https://github.com/user-attachments/assets/cea4282f-16d2-4fa2-953e-b7bd2a559584)

**Comment by phil294** [comment]
What exactly do you mean? And is this a new bug since release 0.1.16 15 minutes ago or has it always been like that?

**Comment by dsmeltz** [comment]
I have the issue on the most recent release.  Looks like some the path pieces are missing.
![image](https://github.com/user-attachments/assets/cb6f9479-831a-4c74-9a93-9158b62d74dc)

**Comment by phil294** [comment]
hi @dsmeltz, is the repository you're using here public so I can reproduce? All my local repos show merge commits just fine. I think I've had this bug in the past but can't remember how/when.

(#106)

**Comment by dsmeltz** [comment]
Unfortunately, it is not.

**Comment by dsmeltz** [comment]
Let try this repo: https://github.com/dsmeltz/dasblog-core.git
VS Code Git
![image](https://github.com/user-attachments/assets/c8b454d3-5ecf-470c-8f2e-ef1e2367fed7)

GitLG
![image](https://github.com/user-attachments/assets/62acf7b9-e01d-48c4-9913-a0f32167854c)

There are some minor differences which I believe are showing the issue.

**Comment by phil294** [comment]
I've released a new version v0.1.18 that fixes the reproducable one. Please try it out. Doesn't mean there could be other bugs too yet unknown.

@heartacker If this doesn't fix it for you, please provide more details

**Comment by phil294** [comment]
(this bug was not introduced in v0.1.16 though, pretty old probably)
