### ISSUE TITLE
Branch merges are not highlighted and are missing the connection flows

### ISSUE THREAD

**Issue by gullevek** [phil294/GitLG#106]
If I run git on the command line I get the following graph output,

<img width="246" alt="Screenshot 2024-09-30 at 9 24 11" src="https://github.com/user-attachments/assets/62c98a86-1e1d-415e-b331-bbc32f3f71cb">

but in the extension (with the `git log --graph --oneline --date=iso-local --pretty={EXT_FORMAT} -n 15000 --skip=0 --all {STASH_REFS} --color=never --invert-grep --extended-regexp --grep="^untracked files on " --grep="^index on "    --author-date-order` command) I get the following output

<img width="286" alt="Screenshot 2024-09-30 at 9 23 45" src="https://github.com/user-attachments/assets/2dd70cdd-55c5-4686-93b6-c6a8b2bcf025">

Compared to the VSCode Graph

<img width="103" alt="Screenshot 2024-09-30 at 9 23 39" src="https://github.com/user-attachments/assets/11e10033-ec98-4c29-8a6f-5233e2d38e47">

or the GitLog Graph

<img width="195" alt="Screenshot 2024-09-30 at 9 23 50" src="https://github.com/user-attachments/assets/cded41f3-94d6-416a-9663-9e852692e4ee">

Which all show the merge points correctly

All my settings are default except that I have the detail panel moved to the bottom

**Comment by phil294** [comment]
Hi @gullevek, is the repository you're using here public so I can reproduce? All my local repos show merge commits just fine. I think I've had this bug in the past but can't remember how/when.

**Comment by phil294** [comment]
I've released a new version v0.1.18 that might have fixed this. Please try it out

**Comment by gullevek** [comment]
Better, but not perfect, it closes the final merge, but skips the middle ones. I need to setup a public git repo for checking this

<img width="331" alt="Screenshot 2024-10-01 at 14 45 51" src="https://github.com/user-attachments/assets/310f358f-1ef9-4e29-b1c2-5dfb1491d521">

**Comment by phil294** [comment]
nvm I got it reproduced

**Comment by phil294** [comment]
should be fixed with v0.1.20 later today

**Comment by gullevek** [comment]
Something went wrong during this update and I just get a "command 'git-log--graph.start' not found" error ... Uninstalled and reinstalled, restart vscode, nothing seems to work ...

<img width="277" alt="Screenshot 2024-10-04 at 9 53 22" src="https://github.com/user-attachments/assets/e076bacf-d28d-45b8-bf2c-6c0b2cb579f8">

**Comment by phil294** [comment]
oops, sorry, you're right... my release script and the VSCode build had an error. fixed now (v0.1.21)

**Comment by gullevek** [comment]
Works perfect now!

<img width="194" alt="Screenshot 2024-10-07 at 8 56 53" src="https://github.com/user-attachments/assets/d897b180-953c-481b-929b-52bfefb5603f">
