### ISSUE TITLE
Error message when viewing deleted file

### ISSUE THREAD

**Issue by pgsandstrom** [phil294/GitLG#109]
I worked on a file, tabbed away, checked out another branch where the file did not exist, and then tabbed back to it. Then I received this error message:

`GitLG: An unexpected error happened. Error summary: Error: Error: ENOENT: no such file or directory, realpath '/Users/dfc0764/work/code/carpay-web/src/myfile.ts'. For details, see VSCode developer tools console. Please consider reporting this error.`

I assume what is missing is simply a check if the file actually exists.

I was using MacOS when the error happened.

**Comment by phil294** [comment]
So the file was in a deleted-yet-displayed state, right?

I'd like to not silently ignore all errors in that location to iron out remaining bugs, but adding a file exists check here definitely sounds like the right thing to do.
