### ISSUE TITLE
Need some help figuring an issue

### ISSUE THREAD

**Issue by webJose** [phil294/GitLG#128]
Hello.  This is probably not a bug of this extension, but I do need help with it.

You see, yesterday Git asked me to update.  I did and everything went seemingly well.  However, this extension (and Git Graph also broke) can no longer authenticate.

My company uses a tool that configures Git with a long-lived (I assume) token.  Re-running this configuration tool solves nothing.  So maybe someone could help me figure out how to troubleshoot this issue?  Will be highly appreciated.

**Comment by phil294** [comment]
You'd need to run `git status`, `git log` and `git fetch --all` from the command line (`cd` into the project directory beforehand) and check the output there. But I won't have the capacity to help you debug this much, sorry.
