### ISSUE TITLE
Long branch names overlap with the commit messages

### ISSUE THREAD

**Issue by adalisk-emikhaylov** [phil294/GitLG#44]
![image](https://github.com/phil294/git-log--graph/assets/69473580/67568fc0-cef2-44b8-9a8e-b5aca396d81f)

**Comment by phil294** [comment]
that's true, so what do we do about it? personally I think it's better like now instead of mhutchie/Git Graph, where the branches are instead placed next to the commit message where they don't really belong. You can always show the commit message by hovering it, so it will have a higher z-index, and in my experience the branch tips are more important than the commit messages.

I'd welcome other suggestions or opinions on this, because after all these kinds of adjustments are best based on majority vote.

**Comment by phil294** [comment]
> My idea would be to move the messages to the right to clear the branch names.

sounds like a good idea, but currently very complicated / slow to do. With the pending resizability / customizability update, perhaps.

An easier solution might be to have all subject lines be right-aligned:
![image](https://github.com/phil294/git-log--graph/assets/14108705/5ef4892f-e6fb-48cd-bfb6-75d6e5738f51)

but I'm not really sold on that approach

**Comment by blm768** [comment]
> You can always show the commit message by hovering it, so it will have a higher z-index, and in my experience the branch tips are more important than the commit messages.

I have to admit, I had no idea that hovering would do that. It seems like a workable solution, but there are some trade-offs around discoverability and user effort (needing an extra mouse gesture to activate the hover behavior).

**Comment by yougotwill** [comment]
What about the commit is shown on top of the message but on hover it's opacity becomes 0?

**Comment by phil294** [comment]
> What about the commit is shown on top of the message but on hover it's opacity becomes 0?

so just like now, but in the opposite order? I don't really see an advantage in comparison to the current situation, except that now the commit messages are more important than then branch tips (which I don't think they are). And it also comes at the disadvantage of some branch tips to potentially be *entirely hidden* behind the message (when there are multiple branch tips at the same commit), so you don't even know they are there without mouse movement.

**Comment by yougotwill** [comment]
Sorry @phil294 I'm mistyped I meant showing the **branch name** on top of the commit message and when you hover it disappears and then the commit message is visible.

**Comment by adalisk-emikhaylov** [comment]
@yougotwill Isn't this the current behavior?

@phil294 The only options I see are what I suggested in my first comment, or what Git Graph does. Right-aligning doesn't look good to me as well.

Also Git Graph collapses `foo` and `origin/foo` into a single rect (`origin` | `foo`), perhaps this could help with screen space too.

**Comment by phil294** [comment]
@adalisk-emikhaylov I agree with everything! Your solution was also suggested by @hansu [here](https://github.com/phil294/git-log--graph/issues/28#issuecomment-1619634372).

**Comment by yougotwill** [comment]
@adalisk-emikhaylov Not to my knowledge. There is no hover affect on the branch names. They have a lower opacity by default but I'm suggesting a hover effect when you put your mouse over them and then they become invisible so that you can read the commit message "behind" them.

**Comment by yougotwill** [comment]
But it looks like an alternative solution has been reached so all good 👍

**Comment by yougotwill** [comment]
Dammit disregard my earlier comments @adalisk-emikhaylov You are 100% correct my mistake. The branch names disappear when you hover on the **commit message** and not the branch names themselves which makes complete sense since you need to be able to click on the branch name.

**Comment by JustinGrote** [comment]
Possibly related but on my high DPI (4k) screen, it always overlaps no matter what.
![image](https://github.com/phil294/git-log--graph/assets/15258962/14b797e8-1390-40fb-b024-52ff7df1254e)

**Comment by phil294** [comment]
Fixed in previous release. It now behaves pretty much as mhutchie/git-graph, except you can reveal more by hovering if something is cut off.

**Comment by hansu** [comment]
Nice, thank you!

**Comment by hansu** [comment]
This does not really belong here, but I only want to mention that the Multi-diff viewer (which is new in this release) is really cool!
