### ISSUE TITLE
Unable to open by "Open graph view"

### ISSUE THREAD

**Issue by Flavio78** [phil294/GitLG#82]
With latest version I cannot open window in editor clicking on "Open graph view" button in "Source control".

<img width="225" alt="image" src="https://github.com/phil294/git-log--graph/assets/53538168/f38057be-7657-4e11-a3ae-d4da0662d3d6">

With previous version I can do it.

**Comment by phil294** [comment]
Cannot reproduce. Could you please share your system details? Win/Mac/Linux and Version? And are you using regular VSCode or VSCodium?

Also, please check the bottom Output pane and select `git log --graph` - perhaps some errors are shown here?

**Comment by Flavio78** [comment]
OS: Windows 11 version 23H2; Visual Studio Code: 1.87.1.
When I click the "Open graph view", I read only the message `start command`.
But the Git Log window does not appear in the editor.

**Comment by dimateos** [comment]
Happens to me too. Only able to open the graph view via command. Tried disabling all extensions but this one.

* vscode Version: 1.87.2 (system setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

Same log, but nothing happens:
![image](https://github.com/phil294/git-log--graph/assets/26868611/c7c81676-7d24-417c-ad50-5ff8cdf442cd)

When using the command and there is no open view, works (also when a view is already open):
![image](https://github.com/phil294/git-log--graph/assets/26868611/07c4026c-61ef-422f-8236-b52ed3d514c4)

Notes:
* Using the buttons also do not work when an open view exists and is in focus.
* I use "editor" for "git-log--graph.position"
* Seems like nothing useful is reported even with "git-log--graph.verbose-logging", I still only get "start command" when pressing any "Open graph view" button.

**Comment by phil294** [comment]
Does this problem still exist in the latest version?

**Comment by dimateos** [comment]
Hello!

The button seems to work without issues.

Thanks a lot for your efforts!
