### ISSUE TITLE
[Feature request] View commit in native multi-diff view

### ISSUE THREAD

**Issue by SeijiSuenaga** [phil294/GitLG#83]
VS Code has a fairly new multi-diff view feature: https://code.visualstudio.com/updates/v1_86#_review-multiple-files-in-diff-editor

It'd be nice if this extension's "Changes" file lists, and perhaps commit context menu, had a button to open the relevant diffs in the multi-diff view.

In case it's helpful, looks like the GitLens extension invokes the view here: https://github.com/gitkraken/vscode-gitlens/blob/v14.9.0/src/system/utils.ts#L170-L184

**Comment by dimateos** [comment]
Yeah that would be great, and something git graph wont be including any time soon ;)

Refernce icon:
![image](https://github.com/phil294/git-log--graph/assets/26868611/fc5df6e4-de81-4523-bc9c-3f9eb6f6dc6e)

Reference editor view:
![image](https://github.com/phil294/git-log--graph/assets/26868611/00f80c50-fbe2-4766-8674-fff816717b91)

**Comment by phil294** [comment]
implemented with latest release v0.1.20
